# Generated by Django 4.1.7 on 2023-03-19 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survivalApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(default=1, max_length=2083),
            preserve_default=False,
        ),
    ]
